### ISSUE TITLE
如果接口参数text包含emoji这类字符，google api就会返回403，demo运行结果如下

### ISSUE THREAD

**Issue by ZombieSouls** [17Yuns/Translate_Api_Free#1]
curl --location 'http://localhost:6060/api/Google/translate' \
--header 'Content-Type: application/json' \
--data '{
 "source_lang": "EN",
 "target_lang": "ZH",
 "text": "😊  Black"
}'

响应结果：
{
    "code": 200,
    "data": "Translation not found",
    "pinyin": "Translation not found"
}

**Comment by 17Yuns** [comment]
![image](https://github.com/user-attachments/assets/1a2441ae-54ae-4148-b0a2-2ba063534269)

已修复这个问题，等会会更新.
